$background = rgb({{background | strip}})
$foreground = rgb({{foreground | strip}})

# ~blue
$accent = rgb({{color4 | strip}})

# ~red
$secondary = rgb({{color1 | strip}})

$active_border = $accent $secondary 45deg
$inactive_border = $background
