$background = rgb({{background | strip}})
$foreground = rgb({{foreground | strip}})

# ~blue
$primary = rgb({{color4 | strip}})

# ~red
$on_surface = rgb({{color1 | strip}})

$active_border = $primary $on_surface 45deg
$inactive_border = $background
