## ~/.config/wallust/kitty.sh

# 基础颜色
foreground           {{foreground}}
background           {{background}}
cursor               {{cursor}}

# 黑
color0  {{color0}}
color8  {{color8}}

# 红
color1  {{color1}}
color9  {{color9}}

# 绿
color2  {{color2}}
color10 {{color10}}

# 黄
color3  {{color3}}
color11 {{color11}}

# 蓝
color4  {{color4}}
color12 {{color12}}

# 品红
color5  {{color5}}
color13 {{color13}}

# 青
color6  {{color6}}
color14 {{color14}}

# 白
color7  {{color7}}
color15 {{color15}}