backend = "kmeans"
color_space = "lab"
palette = "dark16"

[filter]
image_filter = "lanczos"

[templates]
hyprland.template = "hyprland-colors.conf"
hyprland.target = "~/.config/hypr/colors.conf"

waybar.template = "waybar-colors.css"
waybar.target = "~/.config/waybar/colors.css"

rofi.template = "rofi-colors.rasi"
rofi.target = "~/.config/rofi/colors.rasi"

kitty.template = "kitty-colors.conf"
kitty.target = "~/.config/kitty/colors.conf"
