$background = rgb(1C1C1E)
$foreground = rgb(FDE3D4)

# ~blue
$primary = rgb(587CB8)

# ~red
$on_surface = rgb(14141D)

$on_primary = $background

$active_border = $primary $on_surface 45deg
$inactive_border = $background
