$background = rgb(1C1F20)
$foreground = rgb(F3F4F4)

# ~blue
$primary = rgb(E7D2CD)

# ~red
$on_surface = rgb(142025)

$on_primary = $background

$active_border = $primary $on_surface 45deg
$inactive_border = $background
