$background = rgb(0E1014)
$foreground = rgb(FFF6CA)

# ~blue
$primary = rgb(ACAC9F)

# ~red
$on_surface = rgb(BD755B)

$on_primary = $background

$active_border = $primary $on_surface 45deg
$inactive_border = $background
