## ~/.config/wallust/kitty.sh

# 基础颜色
foreground           #FFF6CA
background           #0E1014
cursor               #F79CB1

# 黑
color0  #37393C
color8  #ACA378

# 红
color1  #BD755B
color9  #BD755B

# 绿
color2  #F04298
color10 #F04298

# 黄
color3  #9892C3
color11 #9892C3

# 蓝
color4  #ACAC9F
color12 #ACAC9F

# 品红
color5  #54F29E
color13 #54F29E

# 青
color6  #FEE468
color14 #FEE468

# 白
color7  #F6E9AB
color15 #F6E9AB