## ~/.config/wallust/kitty.sh

# 基础颜色
foreground           #F3F4F4
background           #1C1F20
cursor               #939EA3

# 黑
color0  #434546
color8  #A0A1A1

# 红
color1  #142025
color9  #142025

# 绿
color2  #334952
color10 #334952

# 黄
color3  #8BAFB8
color11 #8BAFB8

# 蓝
color4  #E7D2CD
color12 #E7D2CD

# 品红
color5  #C9E1E5
color13 #C9E1E5

# 青
color6  #DCDFDF
color14 #DCDFDF

# 白
color7  #E5E7E7
color15 #E5E7E7