# Environment for xdg-desktop-portal-hyprland
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Start Polkit
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Load Notification Daemon
exec-once = swaync

# Using hypridle to start hyprlock
exec-once = hypridle

# Load cliphist history
exec-once = wl-paste --watch cliphist store

# Load wallpaper
exec-once = swww img $(cat $HOME/.cache/current_wallpaper) --transition-type any

# input method
exec-once = fcitx5 -d
