# --- windows management ---
bind = $mainMod, Q, killactive
bind = $mainMod, F, fullscreen, 0
bind = $mainMod, M, fullscreen, 1
bind = $mainMod, T, togglefloating
bind = $mainMod SHIFT, T, workspaceopt, allfloat
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
binde = ALT,Tab,cyclenext

# --- Applications ---
bind = $mainMod, RETURN, exec, kitty
bind = $mainMod, B, exec, zen-browser
bind = $mainMod, PRINT, exec, satty
bind = $mainMod, E, exec, superfile

# --- Rofi Keybinds ---
bind = ALT, SPACE, exec, rofi -show drun                            # Alt + Space: App Launcher
bind = SUPER, L, exec, ~/.config/rofi/scripts/power.sh              # Win + L: Power Menu (Sleep, Logout...)
bind = SUPER, V, exec, ~/dotfiles/scripts/clipboard.sh              # Win + Shift + V: Clipboard manager
bind = SUPER SHIFT, W, exec, ~/.config/rofi/scripts/wallpaper.sh    # Win + Shift + W: Wallpaper Switcher
bind = SUPER SHIFT, T, exec, ~/.config/rofi/scripts/theme.sh        # Win + Shift + T: Global Theme Switcher
bind = SUPER SHIFT, B, exec, ~/.config/rofi/scripts/waybar.sh       # Win + Shift + B: Waybar Theme Switcher
bind = SUPER SHIFT, C, exec, ~/.config/rofi/scripts/bluetooth.sh    # Win + Shift + C: Bluetooth Connector
bind = SUPER SHIFT, M, exec, ~/.config/rofi/scripts/supergfx.sh     # Win + Shift + M: Graphic card switcher

# Workspaces
bind = $mainMod, 1, workspace, 1  # Open workspace 1
bind = $mainMod, 2, workspace, 2  # Open workspace 2
bind = $mainMod, 3, workspace, 3  # Open workspace 3
bind = $mainMod, 4, workspace, 4  # Open workspace 4
bind = $mainMod, 5, workspace, 5  # Open workspace 5
bind = $mainMod, 6, workspace, 6  # Open workspace 6
bind = $mainMod, 7, workspace, 7  # Open workspace 7
bind = $mainMod, 8, workspace, 8  # Open workspace 8
bind = $mainMod, 9, workspace, 9  # Open workspace 9
bind = $mainMod, 0, workspace, 10 # Open workspace 10

bind = $mainMod SHIFT, 1, movetoworkspace, 1  # Move active window to workspace 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2  # Move active window to workspace 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3  # Move active window to workspace 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4  # Move active window to workspace 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5  # Move active window to workspace 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6  # Move active window to workspace 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7  # Move active window to workspace 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8  # Move active window to workspace 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9  # Move active window to workspace 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10 # Move active window to workspace 10

bind = $mainMod, Tab, workspace, m+1       # Open next workspace
bind = $mainMod SHIFT, Tab, workspace, m-1 # Open previous workspace

bind = , XF86MonBrightnessUp, exec, brightnessctl -q s +10%
bind = , XF86MonBrightnessDown, exec, brightnessctl -q s 10%-
bindle=, XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindle=, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioPause, exec, playerctl pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous
